name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Publish changed images
      uses: dawidd6/action-docker-publish-changed@v3
      with:
        username: ${{secrets.USER}}
        password: ${{secrets.PASS}}
        platforms: linux/amd64,linux/arm64,linux/arm
        tag: latest
